import { Word } from './types';

export interface CuratedTheme {
    id: number;
    title: string;
    description: string;
    count: number;
    level: string;
    icon: string;
    category: string;
    words: Omit<Word, 'id' | 'isMemorized'>[];
}

export const CURATED_THEMES: CuratedTheme[] = [
    {
        id: 30,
        title: '핸드메이드 마켓 판매 전략',
        description: '아이디어스, 에티(Etsy) 등 글로벌 플랫폼 입점부터 마케팅까지 실무 어휘.',
        count: 20,
        level: 'B2+',
        icon: '🧵',
        category: 'Professional',
        words: [
            { term: 'Craftsmanship', definition: 'The quality of design and work shown in something made by hand', meaningKr: '장인 정신', exampleEn: 'The craftsmanship of this leather bag is outstanding.' },
            { term: 'Artisan', definition: 'A worker in a skilled trade, especially one that involves making things by hand', meaningKr: '장인', exampleEn: 'This cheese is produced by local artisans.' },
            { term: 'Bespoke', definition: 'Made for a particular customer or user', meaningKr: '맞춤형의', exampleEn: 'He wears a bespoke suit to the office.' },
            { term: 'Wholesale', definition: 'The selling of goods in large quantities to be retailed by others', meaningKr: '도매', exampleEn: 'We buy the materials wholesale to reduce costs.' },
            { term: 'Retail', definition: 'The sale of goods to the public in relatively small quantities for use or consumption rather than for resale', meaningKr: '소매', exampleEn: 'The retail price is much higher than the manufacturing cost.' },
            { term: 'Profit margin', definition: 'The amount by which revenue from sales exceeds costs in a business', meaningKr: '이윤 여백, 이익률', exampleEn: 'To stay competitive, we need to increase our profit margin.' },
            { term: 'Inventory', definition: 'A complete list of items such as property, goods in stock, or the contents of a building', meaningKr: '재고', exampleEn: 'We need to check the inventory before ordering more supplies.' },
            { term: 'Procurement', definition: 'The action of obtaining or procuring something', meaningKr: '조달', exampleEn: 'She is in charge of the procurement of raw materials.' },
            { term: 'Vendor', definition: 'A person or company offering something for sale', meaningKr: '판매자', exampleEn: 'We are looking for a reliable vendor for our packaging.' },
            { term: 'Overhead', definition: 'Business expenses not directly attributed to creating a product or service', meaningKr: '간접비', exampleEn: 'Reducing overhead is essential for small business survival.' },
            { term: 'Niche market', definition: 'A specialized segment of the market for a particular kind of product or service', meaningKr: '틈새 시장', exampleEn: 'They found a niche market for vegan handmade soaps.' },
            { term: 'Consignment', definition: 'A batch of goods destined for or delivered to someone', meaningKr: '위탁 판매', exampleEn: 'She sells her pottery on consignment at the local gallery.' },
            { term: 'Aesthetic', definition: 'Concerned with beauty or the appreciation of beauty', meaningKr: '미학적인', exampleEn: 'The store has a minimalist aesthetic.' },
            { term: 'Target audience', definition: 'A particular group at which a film, book, advertising campaign, etc., is aimed', meaningKr: '주요 대상층', exampleEn: 'Our target audience is environmentally conscious millennials.' },
            { term: 'Branding', definition: 'The promotion of a particular product or company by means of advertising and distinctive design', meaningKr: '브랜드화', exampleEn: 'Strong branding helped them stand out in the crowded market.' },
            { term: 'Customer retention', definition: 'The ability of a company or product to retain its customers over some specified period', meaningKr: '고객 유지', exampleEn: 'Excellent customer service is key to high customer retention.' },
            { term: 'Logistics', definition: 'The detailed coordination of a complex operation involving many people, facilities, or supplies', meaningKr: '물류', exampleEn: 'Managing international logistics can be challenging.' },
            { term: 'Tariff', definition: 'A tax or duty to be paid on a particular class of imports or exports', meaningKr: '관세', exampleEn: 'High tariffs make exporting to that country difficult.' },
            { term: 'Dropshipping', definition: 'Moving goods from the manufacturer directly to the retailer without going through the usual distribution channels', meaningKr: '직배송', exampleEn: 'Dropshipping reduces the need for large inventory space.' },
            { term: 'Scalability', definition: 'The capacity to be changed in size or scale', meaningKr: '확장성', exampleEn: 'The business model lacks scalability.' },
        ],
    },
    {
        id: 36,
        title: '베이킹의 과학: 발효와 화학',
        description: '이스트 활성화와 마이야르 반응 등 파티시에를 위한 고급 영어.',
        count: 20,
        level: 'C1',
        icon: '🍰',
        category: 'Specialized',
        words: [
            { term: 'Fermentation', definition: 'The chemical breakdown of a substance by bacteria, yeasts, or other microorganisms', meaningKr: '발효', exampleEn: 'Proper fermentation is crucial for making sourdough bread.' },
            { term: 'Kneading', definition: 'Working (dough or clay) into a uniform mixture by pressing, folding, and stretching', meaningKr: '반죽하기', exampleEn: 'Kneading the dough develops the gluten.' },
            { term: 'Proofing', definition: 'A step in the preparation of yeast bread and other baked goods where the dough is allowed to rest and rise', meaningKr: '발효 (부풀리기)', exampleEn: 'The dough needs a second proofing before baking.' },
            { term: 'Maillard reaction', definition: 'A chemical reaction between amino acids and reducing sugars that gives browned food its distinctive flavor', meaningKr: '마이야르 반응', exampleEn: 'The Maillard reaction gives the crust its rich color and flavor.' },
            { term: 'Caramelization', definition: 'The browning of sugar, a process used extensively in cooking for the resulting sweet nutty flavor and brown color', meaningKr: '캐러멜화', exampleEn: 'Caramelization of the onions takes about 30 minutes.' },
            { term: 'Gelatinization', definition: 'The process of breaking down the intermolecular bonds of starch molecules in the presence of water and heat', meaningKr: '호화 (젤라틴화)', exampleEn: 'Starch gelatinization thickens the pastry cream.' },
            { term: 'Gluten', definition: 'A substance present in cereal grains, especially wheat, that is responsible for the elastic texture of dough', meaningKr: '글루텐', exampleEn: 'Strong bread flour has a high gluten content.' },
            { term: 'Leavening agent', definition: 'A substance used in dough or batter to make it rise', meaningKr: '팽창제', exampleEn: 'Baking powder and baking soda are common leavening agents.' },
            { term: 'Hydration', definition: 'The process of causing something to absorb water', meaningKr: '수화', exampleEn: 'High hydration doughs are harder to handle but produce a more open crumb.' },
            { term: 'Crumb', definition: 'The soft inner part of a loaf of bread', meaningKr: '빵 속 (결)', exampleEn: 'This bread has a beautifully soft and airy crumb.' },
            { term: 'Crust', definition: 'The tough outer part of a loaf of bread', meaningKr: '빵 껍질', exampleEn: 'Baking with steam creates a crisp crust.' },
            { term: 'Autolyse', definition: 'A resting period for dough after mixing flour and water, allowing flour to fully hydrate', meaningKr: '오토리즈 (수화 휴지)', exampleEn: 'An autolyse step improves the dough\'s extensibility.' },
            { term: 'Emulsion', definition: 'A fine dispersion of minute droplets of one liquid in another in which it is not soluble or miscible', meaningKr: '유화 (에멀전)', exampleEn: 'Mayonnaise is a classic example of an emulsion.' },
            { term: 'Tempering', definition: 'The process of carefully melting and cooling chocolate to achieve a glossy finish and a crisp snap', meaningKr: '템퍼링 (온도 조절)', exampleEn: 'Tempering chocolate properly is an essential skill for a pastry chef.' },
            { term: 'Denaturation', definition: 'The process modifying the molecular structure of a protein', meaningKr: '변성', exampleEn: 'Heat causes the denaturation of the proteins in the egg.' },
            { term: 'Coagulation', definition: 'The action or process of a liquid, especially blood, changing to a solid or semi-solid state', meaningKr: '응고', exampleEn: 'Coagulation of the egg proteins sets the custard.' },
            { term: 'Viscosity', definition: 'The state of being thick, sticky, and semifluid in consistency, due to internal friction', meaningKr: '점도', exampleEn: 'The viscosity of the batter affects how it spreads in the pan.' },
            { term: 'Aeration', definition: 'The introduction of air into a material', meaningKr: '공기 혼입 (에어레이션)', exampleEn: 'Whipping the cream incorporates aeration for a lighter texture.' },
            { term: 'Retardation', definition: 'The action of delaying or slowing the progress or development of something', meaningKr: '지연 (냉장 발효)', exampleEn: 'Cold retardation improves the flavor complexity of the sourdough.' },
            { term: 'Lamination', definition: 'The process of folding and rolling butter into dough to create thin layers', meaningKr: '접어 밀기 (라미네이션)', exampleEn: 'Lamination is the technique used to make croissants flaky.' },
        ],
    },
    {
        id: 51,
        title: '공공 행정 및 민원 실무',
        description: '지방 자치 단체 조직 구조와 악성 민원 대응 등 공직 사회 격식 표현.',
        count: 20,
        level: 'B2+',
        icon: '🏛️',
        category: 'Public Service',
        words: [
            { term: 'Bureaucracy', definition: 'A system of government in which most of the important decisions are made by state officials rather than by elected representatives', meaningKr: '관료제', exampleEn: 'The process was slowed down by unnecessary bureaucracy.' },
            { term: 'Legislation', definition: 'Laws, considered collectively', meaningKr: '법률 제정, 입법', exampleEn: 'New legislation will be introduced to protect the environment.' },
            { term: 'Regulation', definition: 'A rule or directive made and maintained by an authority', meaningKr: '규정', exampleEn: 'There are strict regulations regarding fire safety.' },
            { term: 'Ordinance', definition: 'An authoritative order; a decree', meaningKr: '조례', exampleEn: 'A city ordinance forbids parking on this street out of hours.' },
            { term: 'Jurisdiction', definition: 'The official power to make legal decisions and judgments', meaningKr: '관할권', exampleEn: 'That matter falls outside our jurisdiction.' },
            { term: 'Constituent', definition: 'Being a voting member of a community or organization and having the power to appoint or elect', meaningKr: '유권자, 선거구민', exampleEn: 'The senator promised to listen to her constituents.' },
            { term: 'Petition', definition: 'A formal written request, typically one signed by many people, appealing to authority with respect to a particular cause', meaningKr: '청원', exampleEn: 'They are collecting signatures for a petition against the new tax.' },
            { term: 'Grievance', definition: 'A real or imagined wrong or other cause for complaint or protest, especially unfair treatment', meaningKr: '불만, 고충', exampleEn: 'A special committee was set up to handle employee grievances.' },
            { term: 'Mediation', definition: 'Intervention in a dispute in order to resolve it; arbitration', meaningKr: '조정', exampleEn: 'The two sides agreed to enter into mediation.' },
            { term: 'De-escalation', definition: 'The reduction of the intensity of a conflict or potentially violent situation', meaningKr: '단계적 축소, 완화', exampleEn: 'Police officers are trained in de-escalation techniques.' },
            { term: 'Litigation', definition: 'The process of taking legal action', meaningKr: '소송', exampleEn: 'The company wishes to avoid litigation if possible.' },
            { term: 'Complainant', definition: 'A plaintiff in certain lawsuits', meaningKr: '원고, 고소인', exampleEn: 'The complainant alleged that she had been unfairly dismissed.' },
            { term: 'Transparency', definition: 'The condition of being transparent', meaningKr: '투명성', exampleEn: 'We demand greater transparency in government spending.' },
            { term: 'Accountability', definition: 'The fact or condition of being accountable; responsibility', meaningKr: '책임성', exampleEn: 'There needs to be more accountability in the public sector.' },
            { term: 'Impartiality', definition: 'Equal treatment of all rivals or disputants; fairness', meaningKr: '공정성', exampleEn: 'The judge must act with complete impartiality.' },
            { term: 'Red tape', definition: 'Excessive bureaucracy or adherence to rules and formalities, especially in public business', meaningKr: '관료적 형식주의', exampleEn: 'Many businesses complain about the amount of red tape they have to deal with.' },
            { term: 'Subpoena', definition: 'A writ ordering a person to attend a court', meaningKr: '소환장', exampleEn: 'He was served with a subpoena to testify in the trial.' },
            { term: 'Compliance', definition: 'The action or fact of complying with a wish or command', meaningKr: '준수', exampleEn: 'The building is in compliance with the new safety codes.' },
            { term: 'Ombudsman', definition: 'An official appointed to investigate individuals\' complaints against maladministration, especially that of public authorities', meaningKr: '옴부즈맨 (고충 처리 담당자)', exampleEn: 'If you are not satisfied, you can complain to the ombudsman.' },
            { term: 'Mandate', definition: 'An official order or commission to do something', meaningKr: '명령, 권한', exampleEn: 'The government has a clear mandate for reform.' },
        ],
    },
    {
        id: 60,
        title: '글로벌 비즈니스 매너',
        description: '해외 파트너와의 협상 및 식사 에티켓에서 쓰이는 세련된 표현.',
        count: 20,
        level: 'B2',
        icon: '🤝',
        category: 'Social Issues',
        words: [
            { term: 'Etiquette', definition: 'The customary code of polite behavior in society or among members of a particular profession or group', meaningKr: '에티켓, 예절', exampleEn: 'It is considered bad etiquette to check your phone during a meeting.' },
            { term: 'Protocol', definition: 'The official procedure or system of rules governing affairs of state or diplomatic occasions', meaningKr: '의전, 프로토콜', exampleEn: 'Strict protocol was followed during the state visit.' },
            { term: 'Nuance', definition: 'A subtle difference in or shade of meaning, expression, or sound', meaningKr: '뉘앙스, 미묘한 차이', exampleEn: 'Cultural nuances play a big role in international negotiations.' },
            { term: 'Consensus', definition: 'A general agreement', meaningKr: '합의', exampleEn: 'It was difficult to reach a consensus among the different departments.' },
            { term: 'Diplomacy', definition: 'The profession, activity, or skill of managing international relations, typically by a country\'s representatives abroad', meaningKr: '외교(적 수완)', exampleEn: 'Handling the difficult client required great diplomacy.' },
            { term: 'Tactful', definition: 'Having or showing tact', meaningKr: '요령 있는, 눈치 있는', exampleEn: 'She gave a very tactful response to the sensitive question.' },
            { term: 'Discretion', definition: 'The quality of behaving or speaking in such a way as to avoid causing offense or revealing private information', meaningKr: '신중함', exampleEn: 'Please handle this matter with the utmost discretion.' },
            { term: 'Rapport', definition: 'A close and harmonious relationship in which the people or groups concerned understand each other\'s feelings or ideas and communicate well', meaningKr: '친밀감, 라포', exampleEn: 'He quickly established a good rapport with the new clients.' },
            { term: 'Counterpart', definition: 'A person or thing holding a position or performing a function that corresponds to that of another person or thing in another place', meaningKr: '상대방', exampleEn: 'The minister held talks with his French counterpart.' },
            { term: 'Banter', definition: 'The playful and friendly exchange of teasing remarks', meaningKr: '가벼운 농담', exampleEn: 'The meeting started with some friendly banter to break the ice.' },
            { term: 'Faux pas', definition: 'An embarrassing or tactless act or remark in a social situation', meaningKr: '실례, 결례', exampleEn: 'Arriving late for the formal dinner was a major faux pas.' },
            { term: 'Courtesy', definition: 'The showing of politeness in one\'s attitude and behavior toward others', meaningKr: '예의', exampleEn: 'It’s just common courtesy to hold the door open for someone.' },
            { term: 'Punctuality', definition: 'The fact or quality of being on time', meaningKr: '시간 엄수', exampleEn: 'Punctuality is highly valued in German business culture.' },
            { term: 'Hierarchy', definition: 'A system or organization in which people or groups are ranked one above the other according to status or authority', meaningKr: '계급 구조, 위계 질서', exampleEn: 'Japanese corporate culture often has a strict hierarchy.' },
            { term: 'Reciprocity', definition: 'The practice of exchanging things with others for mutual benefit, especially privileges granted by one country or organization to another', meaningKr: '상호 이익, 상호주의', exampleEn: 'Gift-giving in business often operates on the principle of reciprocity.' },
            { term: 'Cordial', definition: 'Warm and friendly', meaningKr: '화기애애한', exampleEn: 'The negotiations were conducted in a cordial atmosphere.' },
            { term: 'Small talk', definition: 'Polite conversation about unimportant or uncontroversial matters, especially as engaged in on social occasions', meaningKr: '잡담', exampleEn: 'We made some small talk about the weather before getting down to business.' },
            { term: 'Icebreaker', definition: 'A thing that serves to relieve inhibition or tension between people', meaningKr: '어색함을 깨는 말이나 행동', exampleEn: 'He started with a joke as an icebreaker.' },
            { term: 'Subtle', definition: 'So delicate or precise as to be difficult to analyze or describe', meaningKr: '미묘한', exampleEn: 'There were subtle signs that they were not happy with the proposal.' },
            { term: 'Customary', definition: 'According to the customs or usual practices associated with a particular society, place, or set of circumstances', meaningKr: '관례적인', exampleEn: 'It is customary to bow when greeting someone in Japan.' },
        ],
    },
];
